// <auto-generated />
using System;
using Forgia.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Forgia.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ForgiaDbContext))]
    partial class ForgiaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Forgia.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Forgia.Domain.Entities.FilamentSpool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostPerKg")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentStockG")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FilamentSpools");
                });

            modelBuilder.Entity("Forgia.Domain.Entities.LaborActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Minutes")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("LaborActivities");
                });

            modelBuilder.Entity("Forgia.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MarginRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VatRate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Forgia.Domain.Entities.Plate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FilamentUsageG")
                        .HasColumnType("TEXT");

                    b.Property<long>("PrintTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrinterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpoolId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WasteRate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrinterId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SpoolId");

                    b.ToTable("Plates");
                });

            modelBuilder.Entity("Forgia.Domain.Entities.Printer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaintenanceCostPerH")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PowerW")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PurchaseCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UsefulLifeH")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Printers");
                });

            modelBuilder.Entity("Forgia.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Forgia.Domain.Entities.LaborActivity", b =>
                {
                    b.HasOne("Forgia.Domain.Entities.Order", "Order")
                        .WithMany("LaborActivities")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Forgia.Domain.Entities.Order", b =>
                {
                    b.HasOne("Forgia.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Forgia.Domain.Entities.Plate", b =>
                {
                    b.HasOne("Forgia.Domain.Entities.Printer", "Printer")
                        .WithMany("Plates")
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Forgia.Domain.Entities.Project", "Project")
                        .WithMany("Plates")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Forgia.Domain.Entities.FilamentSpool", "Spool")
                        .WithMany("Plates")
                        .HasForeignKey("SpoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Printer");

                    b.Navigation("Project");

                    b.Navigation("Spool");
                });

            modelBuilder.Entity("Forgia.Domain.Entities.Project", b =>
                {
                    b.HasOne("Forgia.Domain.Entities.Order", "Order")
                        .WithMany("Projects")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Forgia.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Forgia.Domain.Entities.FilamentSpool", b =>
                {
                    b.Navigation("Plates");
                });

            modelBuilder.Entity("Forgia.Domain.Entities.Order", b =>
                {
                    b.Navigation("LaborActivities");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Forgia.Domain.Entities.Printer", b =>
                {
                    b.Navigation("Plates");
                });

            modelBuilder.Entity("Forgia.Domain.Entities.Project", b =>
                {
                    b.Navigation("Plates");
                });
#pragma warning restore 612, 618
        }
    }
}
